stateDiagram

[*] --> InitiateQueue
InitiateQueue --> FetchBranchesFromDatabase
FetchBranchesFromDatabase --> AlignBranchPowerToQueues
AlignBranchPowerToQueues --> ReadyToProcess
ReadyToProcess --> [*]
