erDiagram
    
    Manager

    Restaurant {
        id uuid PK
        name varchar 
        phone varchar
        email varchar
    }

    Branch {
        id uuid PK
        location varchar
    }

    Item {
        id uuid PK
        name varchar
        image varchar
        price float
        sizesAvailable SIZE
        customizations JSON
        preperationTime float
    }
    
    Category {
        name varchar PK
    }

    Restaurant ||--|{ Branch : has
    Restaurant ||--o{ Item : includes
    Manager ||--o| Restaurant : manages
    Manager ||--o| Branch : manages
    Item ||--o| Category : "belongs to"
    Restaurant ||--o| Category : "has"
