erDiagram
    
    Manager {
        id varchar(255) PK
        username varchar(255) UK
        password varchar(255)
        role int
    }

    Restaurant {
        id uuid PK
        name varchar 
        phone varchar
        email varchar
    }

    Branch {
        id uuid PK
        latitude float
        longitude float
        address varchar
        phone varchar
    }

    Item {
        id uuid PK
        name varchar UK
        image varchar
        price float
        sizesAvailable varchar(255)
        customizations JSON
        preperationTime float
    }
    
    Category {
        name varchar
        restaurantId uuid FK
    }

    Table {
        branchId uuid FK
        tableNumber int
        seats int
    }

    Restaurant ||--|{ Branch : has
    Restaurant ||--o{ Item : includes
    Manager ||--o| Restaurant : manages
    Manager ||--o| Branch : manages
    Item ||--o| Category : "belongs to"
    Restaurant ||--o| Category : "has"
    Branch ||--o| Table : has
