name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish application
        run: dotnet publish -c Release -o publish

      - name: Prepare SSH key
      
        run: |
          echo "$EC2_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Copy files to EC2 (~/app)
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ec2_key.pem" \
            ./publish/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app

      - name: Restart systemd service
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "sudo systemctl restart ${{ secrets.SERVICE_NAME }}"