name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'



      - name: Prepare SSH key
      
        run: |
          echo "$EC2_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Copy source code to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ec2_key.pem" \
            ./OrdrMate/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app

      - name: Build on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              cd ~/app
              dotnet restore
          EOF

      - name: Apply Migrations on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              cd ~/app
              dotnet ef database update
          EOF

      - name: Restart Service on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              sudo systemctl restart ${{ secrets.SERVICE_NAME }}
          EOF